# Generated by Django 2.2.8 on 2020-06-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='account',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
