version: '3.1'

volumes:
  init-db:
  # data-db:

services:

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./backend/init-db:/docker-entrypoint-initdb.d
      # - ./backend/data-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DATABASE_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MONGO_INITDB_DATABASE: "${DATABASE_NAME}"
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DATABASE_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DATABASE_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: "${DATABASE_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${DATABASE_PASSWORD}"
    depends_on:
      - mongodb

  make_migrations:
    build: ./backend
    image: api
    command: python manage.py makemigrations
    environment:
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_NAME: "${DATABASE_NAME}"
    volumes:
      - ./backend:/backend
    links:
      - mongodb
    depends_on:
      - mongodb
  
  migration:
    build: ./backend
    image: api
    command: python manage.py migrate
    environment:
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_NAME: "${DATABASE_NAME}"
    volumes:
      - ./backend:/backend
    links:
      - mongodb
    depends_on:
      - make_migrations

  api:
    image: api
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    environment:
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_NAME: "${DATABASE_NAME}"
    links:
      - mongodb
    depends_on:
      - migration
  
  frontend:
    stdin_open: true
    image: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    depends_on:
      - api

